use crate::fields::FieldContent;
use serde::Serialize;

#[derive(Clone, Copy, Debug, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum BodyLocation {
    LeftAbdomen,
    LeftArm,
    LeftBicep,
    LeftBrachioradialis,
    LeftCalf,
    LeftChest,
    LeftForearmExtensors,
    LeftGlute,
    LeftHamstring,
    LeftLeg,
    LeftLowerBack,
    LeftQuad,
    LeftShin,
    LeftShoulder,
    LeftTricep,
    LeftUpperBack,
    Neck,
    RightAbdomen,
    RightArm,
    RightBicep,
    RightBrachioradialis,
    RightCalf,
    RightChest,
    RightForearmExtensors,
    RightGlute,
    RightHamstring,
    RightLeg,
    RightLowerBack,
    RightQuad,
    RightShin,
    RightShoulder,
    RightTricep,
    RightUpperBack,
    Throat,
    TorsoBack,
    TorsoFront,
    WaistFront,
    WaistLeft,
    WaistMidBack,
    WaistRight,
    UnknownValue(u64),
}

impl From<FieldContent> for BodyLocation {
    fn from(field: FieldContent) -> Self {
        if let FieldContent::Enum(enum_value) = field {
            match enum_value {
                0 => BodyLocation::LeftLeg,
                1 => BodyLocation::LeftCalf,
                2 => BodyLocation::LeftShin,
                3 => BodyLocation::LeftHamstring,
                4 => BodyLocation::LeftQuad,
                5 => BodyLocation::LeftGlute,
                6 => BodyLocation::RightLeg,
                7 => BodyLocation::RightCalf,
                8 => BodyLocation::RightShin,
                9 => BodyLocation::RightHamstring,
                10 => BodyLocation::RightQuad,
                11 => BodyLocation::RightGlute,
                12 => BodyLocation::TorsoBack,
                13 => BodyLocation::LeftLowerBack,
                14 => BodyLocation::LeftUpperBack,
                15 => BodyLocation::RightLowerBack,
                16 => BodyLocation::RightUpperBack,
                17 => BodyLocation::TorsoFront,
                18 => BodyLocation::LeftAbdomen,
                19 => BodyLocation::LeftChest,
                20 => BodyLocation::RightAbdomen,
                21 => BodyLocation::RightChest,
                22 => BodyLocation::LeftArm,
                23 => BodyLocation::LeftShoulder,
                24 => BodyLocation::LeftBicep,
                25 => BodyLocation::LeftTricep,
                26 => BodyLocation::LeftBrachioradialis,
                27 => BodyLocation::LeftForearmExtensors,
                28 => BodyLocation::RightArm,
                29 => BodyLocation::RightShoulder,
                30 => BodyLocation::RightBicep,
                31 => BodyLocation::RightTricep,
                32 => BodyLocation::RightBrachioradialis,
                33 => BodyLocation::RightForearmExtensors,
                34 => BodyLocation::Neck,
                35 => BodyLocation::Throat,
                36 => BodyLocation::WaistMidBack,
                37 => BodyLocation::WaistFront,
                38 => BodyLocation::WaistLeft,
                39 => BodyLocation::WaistRight,
                n => BodyLocation::UnknownValue(n as u64),
            }
        } else {
          panic!("can't convert BodyLocation to {:?}", field);
        }
    }
}
