use crate::fields::FieldContent;
use serde::Serialize;

#[derive(Clone, Copy, Debug, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum CoreExerciseName {
    AbdominalLegRotations,
    AbsJabs,
    AlternatingPlateReach,
    AlternatingSlideOut,
    ArmAndLegExtensionOnKnees,
    BarbellRollout,
    BicepCurlWithLegExtension,
    Bicycle,
    BodyBarObliqueTwist,
    CableCorePress,
    CableSideBend,
    CatCow,
    Corkscrew,
    CrescentCircle,
    CrissCross,
    CrissCrossWithBall,
    CyclingRussianTwist,
    DoubleLegStretch,
    ElevatedFeetRussianTwist,
    GhdBackExtensions,
    HalfTurkishGetUp,
    Inchworm,
    KettlebellWindmill,
    KneeFolds,
    KneelingAbWheel,
    LowerLift,
    ModifiedFrontLever,
    NeckPull,
    OpenKneeTucks,
    OverheadWalk,
    PelvicClocks,
    RollOver,
    RollUp,
    Rolling,
    Rowing1,
    Rowing2,
    RussianTwist,
    Scissors,
    SideAbsLegLift,
    SideBend,
    SingleLegCircles,
    SingleLegStretch,
    SnakeTwist1And2,
    Swan,
    Swimming,
    SwissBallJackknife,
    SwissBallPike,
    SwissBallRollout,
    Teaser,
    TheHundred,
    TriangleHipPress,
    TrxSuspendedJackknife,
    UBoat,
    WeightedAbsJabs,
    WeightedAlternatingSlideOut,
    WeightedBarbellRollout,
    WeightedCrescentCircle,
    WeightedCyclingRussianTwist,
    WeightedElevatedFeetRussianTwist,
    WeightedGhdBackExtensions,
    WeightedKneelingAbWheel,
    WeightedModifiedFrontLever,
    WeightedOpenKneeTucks,
    WeightedSideAbsLegLift,
    WeightedSideBend,
    WeightedSwissBallJackknife,
    WeightedSwissBallPike,
    WeightedSwissBallRollout,
    WeightedTriangleHipPress,
    WeightedTrxSuspendedJackknife,
    WeightedUBoat,
    WeightedWindmillSwitches,
    WindmillSwitches,
    UnknownValue(u64),
}

impl From<FieldContent> for CoreExerciseName {
    fn from(field: FieldContent) -> Self {
        if let FieldContent::UnsignedInt16(enum_value) = field {
            match enum_value {
                0 => CoreExerciseName::AbsJabs,
                1 => CoreExerciseName::WeightedAbsJabs,
                2 => CoreExerciseName::AlternatingPlateReach,
                3 => CoreExerciseName::BarbellRollout,
                4 => CoreExerciseName::WeightedBarbellRollout,
                5 => CoreExerciseName::BodyBarObliqueTwist,
                6 => CoreExerciseName::CableCorePress,
                7 => CoreExerciseName::CableSideBend,
                8 => CoreExerciseName::SideBend,
                9 => CoreExerciseName::WeightedSideBend,
                10 => CoreExerciseName::CrescentCircle,
                11 => CoreExerciseName::WeightedCrescentCircle,
                12 => CoreExerciseName::CyclingRussianTwist,
                13 => CoreExerciseName::WeightedCyclingRussianTwist,
                14 => CoreExerciseName::ElevatedFeetRussianTwist,
                15 => CoreExerciseName::WeightedElevatedFeetRussianTwist,
                16 => CoreExerciseName::HalfTurkishGetUp,
                17 => CoreExerciseName::KettlebellWindmill,
                18 => CoreExerciseName::KneelingAbWheel,
                19 => CoreExerciseName::WeightedKneelingAbWheel,
                20 => CoreExerciseName::ModifiedFrontLever,
                21 => CoreExerciseName::OpenKneeTucks,
                22 => CoreExerciseName::WeightedOpenKneeTucks,
                23 => CoreExerciseName::SideAbsLegLift,
                24 => CoreExerciseName::WeightedSideAbsLegLift,
                25 => CoreExerciseName::SwissBallJackknife,
                26 => CoreExerciseName::WeightedSwissBallJackknife,
                27 => CoreExerciseName::SwissBallPike,
                28 => CoreExerciseName::WeightedSwissBallPike,
                29 => CoreExerciseName::SwissBallRollout,
                30 => CoreExerciseName::WeightedSwissBallRollout,
                31 => CoreExerciseName::TriangleHipPress,
                32 => CoreExerciseName::WeightedTriangleHipPress,
                33 => CoreExerciseName::TrxSuspendedJackknife,
                34 => CoreExerciseName::WeightedTrxSuspendedJackknife,
                35 => CoreExerciseName::UBoat,
                36 => CoreExerciseName::WeightedUBoat,
                37 => CoreExerciseName::WindmillSwitches,
                38 => CoreExerciseName::WeightedWindmillSwitches,
                39 => CoreExerciseName::AlternatingSlideOut,
                40 => CoreExerciseName::WeightedAlternatingSlideOut,
                41 => CoreExerciseName::GhdBackExtensions,
                42 => CoreExerciseName::WeightedGhdBackExtensions,
                43 => CoreExerciseName::OverheadWalk,
                44 => CoreExerciseName::Inchworm,
                45 => CoreExerciseName::WeightedModifiedFrontLever,
                46 => CoreExerciseName::RussianTwist,
                47 => CoreExerciseName::AbdominalLegRotations,
                48 => CoreExerciseName::ArmAndLegExtensionOnKnees,
                49 => CoreExerciseName::Bicycle,
                50 => CoreExerciseName::BicepCurlWithLegExtension,
                51 => CoreExerciseName::CatCow,
                52 => CoreExerciseName::Corkscrew,
                53 => CoreExerciseName::CrissCross,
                54 => CoreExerciseName::CrissCrossWithBall,
                55 => CoreExerciseName::DoubleLegStretch,
                56 => CoreExerciseName::KneeFolds,
                57 => CoreExerciseName::LowerLift,
                58 => CoreExerciseName::NeckPull,
                59 => CoreExerciseName::PelvicClocks,
                60 => CoreExerciseName::RollOver,
                61 => CoreExerciseName::RollUp,
                62 => CoreExerciseName::Rolling,
                63 => CoreExerciseName::Rowing1,
                64 => CoreExerciseName::Rowing2,
                65 => CoreExerciseName::Scissors,
                66 => CoreExerciseName::SingleLegCircles,
                67 => CoreExerciseName::SingleLegStretch,
                68 => CoreExerciseName::SnakeTwist1And2,
                69 => CoreExerciseName::Swan,
                70 => CoreExerciseName::Swimming,
                71 => CoreExerciseName::Teaser,
                72 => CoreExerciseName::TheHundred,
                n => CoreExerciseName::UnknownValue(n as u64),
            }
        } else {
          panic!("can't convert CoreExerciseName to {:?}", field);
        }
    }
}
