use crate::fields::FieldContent;
use serde::Serialize;

#[derive(Clone, Copy, Debug, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum CrunchExerciseName {
    BicycleCrunch,
    CableCrunch,
    CircularArmCrunch,
    CrossLegReverseCrunch,
    CrossedArmsCrunch,
    Crunch,
    CrunchChop,
    DoubleCrunch,
    ElbowToKneeCrunch,
    FlutterKicks,
    FoamRollerReverseCrunchOnBench,
    FoamRollerReverseCrunchWithDumbbell,
    FoamRollerReverseCrunchWithMedicineBall,
    FrogPress,
    HangingKneeRaiseObliqueCrunch,
    HipCrossover,
    HollowRock,
    InclineReverseCrunch,
    KneelingCableCrunch,
    KneelingCrossCrunch,
    KneelingObliqueCableCrunch,
    KneesToElbow,
    LegExtensions,
    LegLevers,
    McgillCurlUp,
    ModifiedPilatesRollUpWithBall,
    PilatesCrunch,
    PilatesRollUpWithBall,
    RaisedLegsCrunch,
    ReverseCrunch,
    ReverseCrunchOnABench,
    ReverseCurlAndLift,
    RotationalLift,
    SeatedAlternatingReverseCrunch,
    SeatedLegU,
    SideToSideCrunchAndWeave,
    SingleLegReverseCrunch,
    SkaterCrunchCross,
    StandingCableCrunch,
    StandingSideCrunch,
    StepClimb,
    StraightLegCrunchWithBall,
    SwissBallCrunch,
    SwissBallReverseCrunch,
    SwissBallRussianTwist,
    SwissBallSideCrunch,
    ThoracicCrunchesOnFoamRoller,
    ToesToBar,
    TricepsCrunch,
    WeightedBicycleCrunch,
    WeightedCrossLegReverseCrunch,
    WeightedCrossedArmsCrunch,
    WeightedCrunch,
    WeightedCrunchChop,
    WeightedDoubleCrunch,
    WeightedElbowToKneeCrunch,
    WeightedFlutterKicks,
    WeightedFoamRollerReverseCrunchOnBench,
    WeightedHangingKneeRaiseObliqueCrunch,
    WeightedHipCrossover,
    WeightedHollowRock,
    WeightedInclineReverseCrunch,
    WeightedKneelingCrossCrunch,
    WeightedLegExtensions,
    WeightedMcgillCurlUp,
    WeightedModifiedPilatesRollUpWithBall,
    WeightedPilatesCrunch,
    WeightedPilatesRollUpWithBall,
    WeightedRaisedLegsCrunch,
    WeightedReverseCrunch,
    WeightedReverseCrunchOnABench,
    WeightedReverseCurlAndLift,
    WeightedRotationalLift,
    WeightedSeatedAlternatingReverseCrunch,
    WeightedSeatedLegU,
    WeightedSideToSideCrunchAndWeave,
    WeightedSingleLegReverseCrunch,
    WeightedSkaterCrunchCross,
    WeightedStepClimb,
    WeightedSwissBallCrunch,
    WeightedSwissBallReverseCrunch,
    WeightedSwissBallRussianTwist,
    WeightedSwissBallSideCrunch,
    WeightedThoracicCrunchesOnFoamRoller,
    WeightedToesToBar,
    UnknownValue(u64),
}

impl From<FieldContent> for CrunchExerciseName {
    fn from(field: FieldContent) -> Self {
        if let FieldContent::UnsignedInt16(enum_value) = field {
            match enum_value {
                0 => CrunchExerciseName::BicycleCrunch,
                1 => CrunchExerciseName::CableCrunch,
                2 => CrunchExerciseName::CircularArmCrunch,
                3 => CrunchExerciseName::CrossedArmsCrunch,
                4 => CrunchExerciseName::WeightedCrossedArmsCrunch,
                5 => CrunchExerciseName::CrossLegReverseCrunch,
                6 => CrunchExerciseName::WeightedCrossLegReverseCrunch,
                7 => CrunchExerciseName::CrunchChop,
                8 => CrunchExerciseName::WeightedCrunchChop,
                9 => CrunchExerciseName::DoubleCrunch,
                10 => CrunchExerciseName::WeightedDoubleCrunch,
                11 => CrunchExerciseName::ElbowToKneeCrunch,
                12 => CrunchExerciseName::WeightedElbowToKneeCrunch,
                13 => CrunchExerciseName::FlutterKicks,
                14 => CrunchExerciseName::WeightedFlutterKicks,
                15 => CrunchExerciseName::FoamRollerReverseCrunchOnBench,
                16 => CrunchExerciseName::WeightedFoamRollerReverseCrunchOnBench,
                17 => CrunchExerciseName::FoamRollerReverseCrunchWithDumbbell,
                18 => CrunchExerciseName::FoamRollerReverseCrunchWithMedicineBall,
                19 => CrunchExerciseName::FrogPress,
                20 => CrunchExerciseName::HangingKneeRaiseObliqueCrunch,
                21 => CrunchExerciseName::WeightedHangingKneeRaiseObliqueCrunch,
                22 => CrunchExerciseName::HipCrossover,
                23 => CrunchExerciseName::WeightedHipCrossover,
                24 => CrunchExerciseName::HollowRock,
                25 => CrunchExerciseName::WeightedHollowRock,
                26 => CrunchExerciseName::InclineReverseCrunch,
                27 => CrunchExerciseName::WeightedInclineReverseCrunch,
                28 => CrunchExerciseName::KneelingCableCrunch,
                29 => CrunchExerciseName::KneelingCrossCrunch,
                30 => CrunchExerciseName::WeightedKneelingCrossCrunch,
                31 => CrunchExerciseName::KneelingObliqueCableCrunch,
                32 => CrunchExerciseName::KneesToElbow,
                33 => CrunchExerciseName::LegExtensions,
                34 => CrunchExerciseName::WeightedLegExtensions,
                35 => CrunchExerciseName::LegLevers,
                36 => CrunchExerciseName::McgillCurlUp,
                37 => CrunchExerciseName::WeightedMcgillCurlUp,
                38 => CrunchExerciseName::ModifiedPilatesRollUpWithBall,
                39 => CrunchExerciseName::WeightedModifiedPilatesRollUpWithBall,
                40 => CrunchExerciseName::PilatesCrunch,
                41 => CrunchExerciseName::WeightedPilatesCrunch,
                42 => CrunchExerciseName::PilatesRollUpWithBall,
                43 => CrunchExerciseName::WeightedPilatesRollUpWithBall,
                44 => CrunchExerciseName::RaisedLegsCrunch,
                45 => CrunchExerciseName::WeightedRaisedLegsCrunch,
                46 => CrunchExerciseName::ReverseCrunch,
                47 => CrunchExerciseName::WeightedReverseCrunch,
                48 => CrunchExerciseName::ReverseCrunchOnABench,
                49 => CrunchExerciseName::WeightedReverseCrunchOnABench,
                50 => CrunchExerciseName::ReverseCurlAndLift,
                51 => CrunchExerciseName::WeightedReverseCurlAndLift,
                52 => CrunchExerciseName::RotationalLift,
                53 => CrunchExerciseName::WeightedRotationalLift,
                54 => CrunchExerciseName::SeatedAlternatingReverseCrunch,
                55 => CrunchExerciseName::WeightedSeatedAlternatingReverseCrunch,
                56 => CrunchExerciseName::SeatedLegU,
                57 => CrunchExerciseName::WeightedSeatedLegU,
                58 => CrunchExerciseName::SideToSideCrunchAndWeave,
                59 => CrunchExerciseName::WeightedSideToSideCrunchAndWeave,
                60 => CrunchExerciseName::SingleLegReverseCrunch,
                61 => CrunchExerciseName::WeightedSingleLegReverseCrunch,
                62 => CrunchExerciseName::SkaterCrunchCross,
                63 => CrunchExerciseName::WeightedSkaterCrunchCross,
                64 => CrunchExerciseName::StandingCableCrunch,
                65 => CrunchExerciseName::StandingSideCrunch,
                66 => CrunchExerciseName::StepClimb,
                67 => CrunchExerciseName::WeightedStepClimb,
                68 => CrunchExerciseName::SwissBallCrunch,
                69 => CrunchExerciseName::SwissBallReverseCrunch,
                70 => CrunchExerciseName::WeightedSwissBallReverseCrunch,
                71 => CrunchExerciseName::SwissBallRussianTwist,
                72 => CrunchExerciseName::WeightedSwissBallRussianTwist,
                73 => CrunchExerciseName::SwissBallSideCrunch,
                74 => CrunchExerciseName::WeightedSwissBallSideCrunch,
                75 => CrunchExerciseName::ThoracicCrunchesOnFoamRoller,
                76 => CrunchExerciseName::WeightedThoracicCrunchesOnFoamRoller,
                77 => CrunchExerciseName::TricepsCrunch,
                78 => CrunchExerciseName::WeightedBicycleCrunch,
                79 => CrunchExerciseName::WeightedCrunch,
                80 => CrunchExerciseName::WeightedSwissBallCrunch,
                81 => CrunchExerciseName::ToesToBar,
                82 => CrunchExerciseName::WeightedToesToBar,
                83 => CrunchExerciseName::Crunch,
                84 => CrunchExerciseName::StraightLegCrunchWithBall,
                n => CrunchExerciseName::UnknownValue(n as u64),
            }
        } else {
          panic!("can't convert CrunchExerciseName to {:?}", field);
        }
    }
}
