use crate::fields::FieldContent;
use serde::Serialize;

#[derive(Clone, Copy, Debug, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum CurlExerciseName {
    AlternatingDumbbellBicepsCurl,
    AlternatingDumbbellBicepsCurlOnSwissBall,
    AlternatingInclineDumbbellBicepsCurl,
    BarbellBicepsCurl,
    BarbellReverseWristCurl,
    BarbellWristCurl,
    BehindTheBackBarbellReverseWristCurl,
    BehindTheBackOneArmCableCurl,
    CableBicepsCurl,
    CableHammerCurl,
    CheatingBarbellBicepsCurl,
    CloseGripEzBarBicepsCurl,
    CrossBodyDumbbellHammerCurl,
    DeadHangBicepsCurl,
    DeclineHammerCurl,
    DumbbellBicepsCurlWithStaticHold,
    DumbbellHammerCurl,
    DumbbellReverseWristCurl,
    DumbbellWristCurl,
    EzBarPreacherCurl,
    ForwardBendBicepsCurl,
    HammerCurlToPress,
    InclineDumbbellBicepsCurl,
    InclineOffsetThumbDumbbellCurl,
    KettlebellBicepsCurl,
    LyingConcentrationCableCurl,
    OneArmPreacherCurl,
    PlatePinchCurl,
    PreacherCurlWithCable,
    ReverseEzBarCurl,
    ReverseGripBarbellBicepsCurl,
    ReverseGripWristCurl,
    SeatedAlternatingDumbbellBicepsCurl,
    SeatedDumbbellBicepsCurl,
    SeatedReverseDumbbellCurl,
    SplitStanceOffsetPinkyDumbbellCurl,
    StandingAlternatingDumbbellCurls,
    StandingDumbbellBicepsCurl,
    StandingEzBarBicepsCurl,
    StaticCurl,
    SwissBallDumbbellOverheadTricepsExtension,
    SwissBallEzBarPreacherCurl,
    TwistingStandingDumbbellBicepsCurl,
    WideGripEzBarBicepsCurl,
    UnknownValue(u64),
}

impl From<FieldContent> for CurlExerciseName {
    fn from(field: FieldContent) -> Self {
        if let FieldContent::UnsignedInt16(enum_value) = field {
            match enum_value {
                0 => CurlExerciseName::AlternatingDumbbellBicepsCurl,
                1 => CurlExerciseName::AlternatingDumbbellBicepsCurlOnSwissBall,
                2 => CurlExerciseName::AlternatingInclineDumbbellBicepsCurl,
                3 => CurlExerciseName::BarbellBicepsCurl,
                4 => CurlExerciseName::BarbellReverseWristCurl,
                5 => CurlExerciseName::BarbellWristCurl,
                6 => CurlExerciseName::BehindTheBackBarbellReverseWristCurl,
                7 => CurlExerciseName::BehindTheBackOneArmCableCurl,
                8 => CurlExerciseName::CableBicepsCurl,
                9 => CurlExerciseName::CableHammerCurl,
                10 => CurlExerciseName::CheatingBarbellBicepsCurl,
                11 => CurlExerciseName::CloseGripEzBarBicepsCurl,
                12 => CurlExerciseName::CrossBodyDumbbellHammerCurl,
                13 => CurlExerciseName::DeadHangBicepsCurl,
                14 => CurlExerciseName::DeclineHammerCurl,
                15 => CurlExerciseName::DumbbellBicepsCurlWithStaticHold,
                16 => CurlExerciseName::DumbbellHammerCurl,
                17 => CurlExerciseName::DumbbellReverseWristCurl,
                18 => CurlExerciseName::DumbbellWristCurl,
                19 => CurlExerciseName::EzBarPreacherCurl,
                20 => CurlExerciseName::ForwardBendBicepsCurl,
                21 => CurlExerciseName::HammerCurlToPress,
                22 => CurlExerciseName::InclineDumbbellBicepsCurl,
                23 => CurlExerciseName::InclineOffsetThumbDumbbellCurl,
                24 => CurlExerciseName::KettlebellBicepsCurl,
                25 => CurlExerciseName::LyingConcentrationCableCurl,
                26 => CurlExerciseName::OneArmPreacherCurl,
                27 => CurlExerciseName::PlatePinchCurl,
                28 => CurlExerciseName::PreacherCurlWithCable,
                29 => CurlExerciseName::ReverseEzBarCurl,
                30 => CurlExerciseName::ReverseGripWristCurl,
                31 => CurlExerciseName::ReverseGripBarbellBicepsCurl,
                32 => CurlExerciseName::SeatedAlternatingDumbbellBicepsCurl,
                33 => CurlExerciseName::SeatedDumbbellBicepsCurl,
                34 => CurlExerciseName::SeatedReverseDumbbellCurl,
                35 => CurlExerciseName::SplitStanceOffsetPinkyDumbbellCurl,
                36 => CurlExerciseName::StandingAlternatingDumbbellCurls,
                37 => CurlExerciseName::StandingDumbbellBicepsCurl,
                38 => CurlExerciseName::StandingEzBarBicepsCurl,
                39 => CurlExerciseName::StaticCurl,
                40 => CurlExerciseName::SwissBallDumbbellOverheadTricepsExtension,
                41 => CurlExerciseName::SwissBallEzBarPreacherCurl,
                42 => CurlExerciseName::TwistingStandingDumbbellBicepsCurl,
                43 => CurlExerciseName::WideGripEzBarBicepsCurl,
                n => CurlExerciseName::UnknownValue(n as u64),
            }
        } else {
          panic!("can't convert CurlExerciseName to {:?}", field);
        }
    }
}
