use crate::fields::FieldContent;
use serde::Serialize;

#[derive(Clone, Copy, Debug, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum HipRaiseExerciseName {
    BarbellHipThrustOnFloor,
    BarbellHipThrustWithBench,
    BentKneeSwissBallReverseHipRaise,
    BridgeWithLegExtension,
    ClamBridge,
    Clams,
    FrontKickTabletop,
    HipExtensionAndCross,
    HipRaise,
    HipRaiseWithFeetOnSwissBall,
    HipRaiseWithHeadOnBosuBall,
    HipRaiseWithHeadOnSwissBall,
    HipRaiseWithKneeSqueeze,
    InclineRearLegExtension,
    InnerThighCircles,
    InnerThighSideLift,
    KettlebellSwing,
    LegCircles,
    LegLift,
    LegLiftInExternalRotation,
    MarchingHipRaise,
    MarchingHipRaiseWithFeetOnASwissBall,
    ReverseHipRaise,
    SingleLegHipRaise,
    SingleLegHipRaiseWithFootOnBench,
    SingleLegHipRaiseWithFootOnBosuBall,
    SingleLegHipRaiseWithFootOnFoamRoller,
    SingleLegHipRaiseWithFootOnMedicineBall,
    SingleLegHipRaiseWithHeadOnBosuBall,
    SingleLegSwissBallHipRaiseAndLegCurl,
    WeightedBentKneeSwissBallReverseHipRaise,
    WeightedBridgeWithLegExtension,
    WeightedClamBridge,
    WeightedFrontKickTabletop,
    WeightedHipExtensionAndCross,
    WeightedHipRaise,
    WeightedHipRaiseWithFeetOnSwissBall,
    WeightedHipRaiseWithHeadOnBosuBall,
    WeightedHipRaiseWithHeadOnSwissBall,
    WeightedHipRaiseWithKneeSqueeze,
    WeightedInclineRearLegExtension,
    WeightedMarchingHipRaise,
    WeightedMarchingHipRaiseWithFeetOnASwissBall,
    WeightedReverseHipRaise,
    WeightedSingleLegHipRaise,
    WeightedSingleLegHipRaiseWithFootOnBench,
    WeightedSingleLegHipRaiseWithFootOnBosuBall,
    WeightedSingleLegHipRaiseWithFootOnFoamRoller,
    WeightedSingleLegHipRaiseWithFootOnMedicineBall,
    WeightedSingleLegHipRaiseWithHeadOnBosuBall,
    UnknownValue(u64),
}

impl From<FieldContent> for HipRaiseExerciseName {
    fn from(field: FieldContent) -> Self {
        if let FieldContent::UnsignedInt16(enum_value) = field {
            match enum_value {
                0 => HipRaiseExerciseName::BarbellHipThrustOnFloor,
                1 => HipRaiseExerciseName::BarbellHipThrustWithBench,
                2 => HipRaiseExerciseName::BentKneeSwissBallReverseHipRaise,
                3 => HipRaiseExerciseName::WeightedBentKneeSwissBallReverseHipRaise,
                4 => HipRaiseExerciseName::BridgeWithLegExtension,
                5 => HipRaiseExerciseName::WeightedBridgeWithLegExtension,
                6 => HipRaiseExerciseName::ClamBridge,
                7 => HipRaiseExerciseName::FrontKickTabletop,
                8 => HipRaiseExerciseName::WeightedFrontKickTabletop,
                9 => HipRaiseExerciseName::HipExtensionAndCross,
                10 => HipRaiseExerciseName::WeightedHipExtensionAndCross,
                11 => HipRaiseExerciseName::HipRaise,
                12 => HipRaiseExerciseName::WeightedHipRaise,
                13 => HipRaiseExerciseName::HipRaiseWithFeetOnSwissBall,
                14 => HipRaiseExerciseName::WeightedHipRaiseWithFeetOnSwissBall,
                15 => HipRaiseExerciseName::HipRaiseWithHeadOnBosuBall,
                16 => HipRaiseExerciseName::WeightedHipRaiseWithHeadOnBosuBall,
                17 => HipRaiseExerciseName::HipRaiseWithHeadOnSwissBall,
                18 => HipRaiseExerciseName::WeightedHipRaiseWithHeadOnSwissBall,
                19 => HipRaiseExerciseName::HipRaiseWithKneeSqueeze,
                20 => HipRaiseExerciseName::WeightedHipRaiseWithKneeSqueeze,
                21 => HipRaiseExerciseName::InclineRearLegExtension,
                22 => HipRaiseExerciseName::WeightedInclineRearLegExtension,
                23 => HipRaiseExerciseName::KettlebellSwing,
                24 => HipRaiseExerciseName::MarchingHipRaise,
                25 => HipRaiseExerciseName::WeightedMarchingHipRaise,
                26 => HipRaiseExerciseName::MarchingHipRaiseWithFeetOnASwissBall,
                27 => HipRaiseExerciseName::WeightedMarchingHipRaiseWithFeetOnASwissBall,
                28 => HipRaiseExerciseName::ReverseHipRaise,
                29 => HipRaiseExerciseName::WeightedReverseHipRaise,
                30 => HipRaiseExerciseName::SingleLegHipRaise,
                31 => HipRaiseExerciseName::WeightedSingleLegHipRaise,
                32 => HipRaiseExerciseName::SingleLegHipRaiseWithFootOnBench,
                33 => HipRaiseExerciseName::WeightedSingleLegHipRaiseWithFootOnBench,
                34 => HipRaiseExerciseName::SingleLegHipRaiseWithFootOnBosuBall,
                35 => HipRaiseExerciseName::WeightedSingleLegHipRaiseWithFootOnBosuBall,
                36 => HipRaiseExerciseName::SingleLegHipRaiseWithFootOnFoamRoller,
                37 => HipRaiseExerciseName::WeightedSingleLegHipRaiseWithFootOnFoamRoller,
                38 => HipRaiseExerciseName::SingleLegHipRaiseWithFootOnMedicineBall,
                39 => HipRaiseExerciseName::WeightedSingleLegHipRaiseWithFootOnMedicineBall,
                40 => HipRaiseExerciseName::SingleLegHipRaiseWithHeadOnBosuBall,
                41 => HipRaiseExerciseName::WeightedSingleLegHipRaiseWithHeadOnBosuBall,
                42 => HipRaiseExerciseName::WeightedClamBridge,
                43 => HipRaiseExerciseName::SingleLegSwissBallHipRaiseAndLegCurl,
                44 => HipRaiseExerciseName::Clams,
                45 => HipRaiseExerciseName::InnerThighCircles,
                46 => HipRaiseExerciseName::InnerThighSideLift,
                47 => HipRaiseExerciseName::LegCircles,
                48 => HipRaiseExerciseName::LegLift,
                49 => HipRaiseExerciseName::LegLiftInExternalRotation,
                n => HipRaiseExerciseName::UnknownValue(n as u64),
            }
        } else {
          panic!("can't convert HipRaiseExerciseName to {:?}", field);
        }
    }
}
