use crate::fields::FieldContent;
use serde::Serialize;

#[derive(Clone, Copy, Debug, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum HyperextensionExerciseName {
    BackExtensionWithOppositeArmAndLegReach,
    BaseRotations,
    BentKneeReverseHyperextension,
    Cobra,
    HollowHoldAndRoll,
    Kicks,
    KneeRaises,
    KneelingSuperman,
    LatPullDownWithRow,
    MedicineBallDeadliftToReach,
    OneArmOneLegRow,
    OneArmRowWithBand,
    OverheadLungeWithMedicineBall,
    PlankKneeTucks,
    SideStep,
    SingleLegBackExtension,
    SpineExtension,
    StaticBackExtension,
    SupermanFromFloor,
    SupermanOnSwissBall,
    SupineFloorBarre,
    SwissBallBackExtension,
    SwissBallHyperextension,
    SwissBallOppositeArmAndLegLift,
    WeightedBackExtensionWithOppositeArmAndLegReach,
    WeightedBaseRotations,
    WeightedBentKneeReverseHyperextension,
    WeightedHollowHoldAndRoll,
    WeightedKicks,
    WeightedKneeRaises,
    WeightedKneelingSuperman,
    WeightedPlankKneeTucks,
    WeightedSideStep,
    WeightedSingleLegBackExtension,
    WeightedSpineExtension,
    WeightedStaticBackExtension,
    WeightedSupermanFromFloor,
    WeightedSwissBallBackExtension,
    WeightedSwissBallHyperextension,
    WeightedSwissBallOppositeArmAndLegLift,
    UnknownValue(u64),
}

impl From<FieldContent> for HyperextensionExerciseName {
    fn from(field: FieldContent) -> Self {
        if let FieldContent::UnsignedInt16(enum_value) = field {
            match enum_value {
                0 => HyperextensionExerciseName::BackExtensionWithOppositeArmAndLegReach,
                1 => HyperextensionExerciseName::WeightedBackExtensionWithOppositeArmAndLegReach,
                2 => HyperextensionExerciseName::BaseRotations,
                3 => HyperextensionExerciseName::WeightedBaseRotations,
                4 => HyperextensionExerciseName::BentKneeReverseHyperextension,
                5 => HyperextensionExerciseName::WeightedBentKneeReverseHyperextension,
                6 => HyperextensionExerciseName::HollowHoldAndRoll,
                7 => HyperextensionExerciseName::WeightedHollowHoldAndRoll,
                8 => HyperextensionExerciseName::Kicks,
                9 => HyperextensionExerciseName::WeightedKicks,
                10 => HyperextensionExerciseName::KneeRaises,
                11 => HyperextensionExerciseName::WeightedKneeRaises,
                12 => HyperextensionExerciseName::KneelingSuperman,
                13 => HyperextensionExerciseName::WeightedKneelingSuperman,
                14 => HyperextensionExerciseName::LatPullDownWithRow,
                15 => HyperextensionExerciseName::MedicineBallDeadliftToReach,
                16 => HyperextensionExerciseName::OneArmOneLegRow,
                17 => HyperextensionExerciseName::OneArmRowWithBand,
                18 => HyperextensionExerciseName::OverheadLungeWithMedicineBall,
                19 => HyperextensionExerciseName::PlankKneeTucks,
                20 => HyperextensionExerciseName::WeightedPlankKneeTucks,
                21 => HyperextensionExerciseName::SideStep,
                22 => HyperextensionExerciseName::WeightedSideStep,
                23 => HyperextensionExerciseName::SingleLegBackExtension,
                24 => HyperextensionExerciseName::WeightedSingleLegBackExtension,
                25 => HyperextensionExerciseName::SpineExtension,
                26 => HyperextensionExerciseName::WeightedSpineExtension,
                27 => HyperextensionExerciseName::StaticBackExtension,
                28 => HyperextensionExerciseName::WeightedStaticBackExtension,
                29 => HyperextensionExerciseName::SupermanFromFloor,
                30 => HyperextensionExerciseName::WeightedSupermanFromFloor,
                31 => HyperextensionExerciseName::SwissBallBackExtension,
                32 => HyperextensionExerciseName::WeightedSwissBallBackExtension,
                33 => HyperextensionExerciseName::SwissBallHyperextension,
                34 => HyperextensionExerciseName::WeightedSwissBallHyperextension,
                35 => HyperextensionExerciseName::SwissBallOppositeArmAndLegLift,
                36 => HyperextensionExerciseName::WeightedSwissBallOppositeArmAndLegLift,
                37 => HyperextensionExerciseName::SupermanOnSwissBall,
                38 => HyperextensionExerciseName::Cobra,
                39 => HyperextensionExerciseName::SupineFloorBarre,
                n => HyperextensionExerciseName::UnknownValue(n as u64),
            }
        } else {
          panic!("can't convert HyperextensionExerciseName to {:?}", field);
        }
    }
}
