use crate::fields::FieldContent;
use serde::Serialize;

#[derive(Clone, Copy, Debug, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum LungeExerciseName {
    AlternatingBarbellForwardLunge,
    AlternatingDumbbellLungeWithReach,
    BackFootElevatedDumbbellSplitSquat,
    BarbellBoxLunge,
    BarbellBulgarianSplitSquat,
    BarbellCrossoverLunge,
    BarbellFrontSplitSquat,
    BarbellLunge,
    BarbellReverseLunge,
    BarbellSideLunge,
    BarbellSplitSquat,
    CoreControlRearLunge,
    DiagonalLunge,
    DropLunge,
    DumbbellBoxLunge,
    DumbbellBulgarianSplitSquat,
    DumbbellCrossoverLunge,
    DumbbellDiagonalLunge,
    DumbbellLunge,
    DumbbellLungeAndRotation,
    DumbbellOverheadBulgarianSplitSquat,
    DumbbellReverseLungeToHighKneeAndPress,
    DumbbellSideLunge,
    ElevatedFrontFootBarbellSplitSquat,
    FrontFootElevatedDumbbellSplitSquat,
    GunslingerLunge,
    LawnmowerLunge,
    LowLungeWithIsometricAdduction,
    LowSideToSideLunge,
    Lunge,
    LungeMatrix,
    LungeWithArmReach,
    LungeWithDiagonalReach,
    LungeWithSideBend,
    OffsetDumbbellLunge,
    OffsetDumbbellReverseLunge,
    OverheadBulgarianSplitSquat,
    OverheadDumbbellReverseLunge,
    OverheadDumbbellSplitSquat,
    OverheadLunge,
    OverheadLungeWithRotation,
    ReverseBarbellBoxLunge,
    ReverseBoxLunge,
    ReverseDumbbellBoxLunge,
    ReverseDumbbellCrossoverLunge,
    ReverseDumbbellDiagonalLunge,
    ReverseLungeWithReachBack,
    ReverseLungeWithTwistAndOverheadReach,
    ReverseSlidingBoxLunge,
    ReverseSlidingLunge,
    RunnersLungeToBalance,
    ShiftingSideLunge,
    SideAndCrossoverLunge,
    SideLunge,
    SideLungeAndPress,
    SideLungeJumpOff,
    SideLungeSweep,
    SideLungeToCrossoverTap,
    SideToSideLungeChops,
    SiffJumpLunge,
    SingleArmReverseLungeAndPress,
    SlidingLateralLunge,
    WalkingBarbellLunge,
    WalkingDumbbellLunge,
    WalkingLunge,
    WeightedLunge,
    WeightedLungeMatrix,
    WeightedReverseLungeWithReachBack,
    WeightedReverseLungeWithTwistAndOverheadReach,
    WeightedReverseSlidingBoxLunge,
    WeightedReverseSlidingLunge,
    WeightedRunnersLungeToBalance,
    WeightedSideAndCrossoverLunge,
    WeightedSideLunge,
    WeightedSideLungeSweep,
    WeightedSideLungeToCrossoverTap,
    WeightedSideToSideLungeChops,
    WeightedSiffJumpLunge,
    WeightedSlidingLateralLunge,
    WeightedWalkingLunge,
    WideGripOverheadBarbellSplitSquat,
    UnknownValue(u64),
}

impl From<FieldContent> for LungeExerciseName {
    fn from(field: FieldContent) -> Self {
        if let FieldContent::UnsignedInt16(enum_value) = field {
            match enum_value {
                0 => LungeExerciseName::OverheadLunge,
                1 => LungeExerciseName::LungeMatrix,
                2 => LungeExerciseName::WeightedLungeMatrix,
                3 => LungeExerciseName::AlternatingBarbellForwardLunge,
                4 => LungeExerciseName::AlternatingDumbbellLungeWithReach,
                5 => LungeExerciseName::BackFootElevatedDumbbellSplitSquat,
                6 => LungeExerciseName::BarbellBoxLunge,
                7 => LungeExerciseName::BarbellBulgarianSplitSquat,
                8 => LungeExerciseName::BarbellCrossoverLunge,
                9 => LungeExerciseName::BarbellFrontSplitSquat,
                10 => LungeExerciseName::BarbellLunge,
                11 => LungeExerciseName::BarbellReverseLunge,
                12 => LungeExerciseName::BarbellSideLunge,
                13 => LungeExerciseName::BarbellSplitSquat,
                14 => LungeExerciseName::CoreControlRearLunge,
                15 => LungeExerciseName::DiagonalLunge,
                16 => LungeExerciseName::DropLunge,
                17 => LungeExerciseName::DumbbellBoxLunge,
                18 => LungeExerciseName::DumbbellBulgarianSplitSquat,
                19 => LungeExerciseName::DumbbellCrossoverLunge,
                20 => LungeExerciseName::DumbbellDiagonalLunge,
                21 => LungeExerciseName::DumbbellLunge,
                22 => LungeExerciseName::DumbbellLungeAndRotation,
                23 => LungeExerciseName::DumbbellOverheadBulgarianSplitSquat,
                24 => LungeExerciseName::DumbbellReverseLungeToHighKneeAndPress,
                25 => LungeExerciseName::DumbbellSideLunge,
                26 => LungeExerciseName::ElevatedFrontFootBarbellSplitSquat,
                27 => LungeExerciseName::FrontFootElevatedDumbbellSplitSquat,
                28 => LungeExerciseName::GunslingerLunge,
                29 => LungeExerciseName::LawnmowerLunge,
                30 => LungeExerciseName::LowLungeWithIsometricAdduction,
                31 => LungeExerciseName::LowSideToSideLunge,
                32 => LungeExerciseName::Lunge,
                33 => LungeExerciseName::WeightedLunge,
                34 => LungeExerciseName::LungeWithArmReach,
                35 => LungeExerciseName::LungeWithDiagonalReach,
                36 => LungeExerciseName::LungeWithSideBend,
                37 => LungeExerciseName::OffsetDumbbellLunge,
                38 => LungeExerciseName::OffsetDumbbellReverseLunge,
                39 => LungeExerciseName::OverheadBulgarianSplitSquat,
                40 => LungeExerciseName::OverheadDumbbellReverseLunge,
                41 => LungeExerciseName::OverheadDumbbellSplitSquat,
                42 => LungeExerciseName::OverheadLungeWithRotation,
                43 => LungeExerciseName::ReverseBarbellBoxLunge,
                44 => LungeExerciseName::ReverseBoxLunge,
                45 => LungeExerciseName::ReverseDumbbellBoxLunge,
                46 => LungeExerciseName::ReverseDumbbellCrossoverLunge,
                47 => LungeExerciseName::ReverseDumbbellDiagonalLunge,
                48 => LungeExerciseName::ReverseLungeWithReachBack,
                49 => LungeExerciseName::WeightedReverseLungeWithReachBack,
                50 => LungeExerciseName::ReverseLungeWithTwistAndOverheadReach,
                51 => LungeExerciseName::WeightedReverseLungeWithTwistAndOverheadReach,
                52 => LungeExerciseName::ReverseSlidingBoxLunge,
                53 => LungeExerciseName::WeightedReverseSlidingBoxLunge,
                54 => LungeExerciseName::ReverseSlidingLunge,
                55 => LungeExerciseName::WeightedReverseSlidingLunge,
                56 => LungeExerciseName::RunnersLungeToBalance,
                57 => LungeExerciseName::WeightedRunnersLungeToBalance,
                58 => LungeExerciseName::ShiftingSideLunge,
                59 => LungeExerciseName::SideAndCrossoverLunge,
                60 => LungeExerciseName::WeightedSideAndCrossoverLunge,
                61 => LungeExerciseName::SideLunge,
                62 => LungeExerciseName::WeightedSideLunge,
                63 => LungeExerciseName::SideLungeAndPress,
                64 => LungeExerciseName::SideLungeJumpOff,
                65 => LungeExerciseName::SideLungeSweep,
                66 => LungeExerciseName::WeightedSideLungeSweep,
                67 => LungeExerciseName::SideLungeToCrossoverTap,
                68 => LungeExerciseName::WeightedSideLungeToCrossoverTap,
                69 => LungeExerciseName::SideToSideLungeChops,
                70 => LungeExerciseName::WeightedSideToSideLungeChops,
                71 => LungeExerciseName::SiffJumpLunge,
                72 => LungeExerciseName::WeightedSiffJumpLunge,
                73 => LungeExerciseName::SingleArmReverseLungeAndPress,
                74 => LungeExerciseName::SlidingLateralLunge,
                75 => LungeExerciseName::WeightedSlidingLateralLunge,
                76 => LungeExerciseName::WalkingBarbellLunge,
                77 => LungeExerciseName::WalkingDumbbellLunge,
                78 => LungeExerciseName::WalkingLunge,
                79 => LungeExerciseName::WeightedWalkingLunge,
                80 => LungeExerciseName::WideGripOverheadBarbellSplitSquat,
                n => LungeExerciseName::UnknownValue(n as u64),
            }
        } else {
          panic!("can't convert LungeExerciseName to {:?}", field);
        }
    }
}
