use crate::fields::FieldContent;
use serde::Serialize;

#[derive(Clone, Copy, Debug, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum Manufacturer {
    AAndD,
    AceSensor,
    AcornProjectsAps,
    Actigraphcorp,
    AlatechTechnologyLtd,
    Archinoetics,
    Beurer,
    Bf1Systems,
    Bkool,
    BodyBikeSmart,
    Bontrager,
    Breakaway,
    BrimBrothers,
    Bryton,
    BrytonSensors,
    BsxAthletics,
    CampagnoloSrl,
    Cardiosport,
    Cateye,
    Ciclosport,
    CitizenSystems,
    CleanMobile,
    Cobi,
    Concept2,
    Coros,
    Cosinuss,
    Cycligentinc,
    Cycliq,
    Dabuziduo,
    Dayton,
    Development,
    Dexcom,
    DirectionTechnology,
    DkCity,
    Dynastream,
    DynastreamOem,
    Dynovelo,
    Echowell,
    Elite,
    Evesports,
    FalcoEMotors,
    FaveroElectronics,
    Feedbacksports,
    Fitcare,
    FourIIIIs,
    Fullspeedahead,
    Garmin,
    GarminFr405Antfs,
    Geonaute,
    GiantManufacturingCo,
    GopherSport,
    Gpulse,
    Hammerhead,
    Healthandlife,
    Hmm,
    Holux,
    Ibike,
    Icg,
    IdBike,
    Idt,
    IforPowell,
    Igpsport,
    Inpeak,
    InsideRideTechnologies,
    Jetblack,
    JohnsonHealthTech,
    Kinetic,
    KineticByKurt,
    LatitudeLimited,
    LemondFitness,
    Lezyne,
    LifeTimeFitness,
    Lifebeam,
    LimitsTechnology,
    Look,
    Luxottica,
    Magellan,
    Magene,
    Magneticdays,
    Magtonic,
    Magura,
    MaxwellGuider,
    Metalogics,
    Metrigear,
    MiPulse,
    Minoura,
    MioMagellan,
    MioTechnologyEurope,
    Moxy,
    Nautilus,
    Navman,
    NciTechnology,
    NielsenKellerman,
    NorthPoleEngineering,
    OctaneFitness,
    Omata,
    OneGiantLeap,
    OnePartCarbon,
    Orangetheory,
    Osynce,
    Peaksware,
    PedalBrain,
    PerceptionDigital,
    Peripedal,
    PhysicalEnterprises,
    Pioneer,
    Podoon,
    PolarElectro,
    Powerbahn,
    Praxisworks,
    Precor,
    Quarq,
    Recon,
    Rotor,
    Salutron,
    Saris,
    Saxonar,
    Scosche,
    ScribeLabs,
    Seesense,
    SeikoEpson,
    SeikoEpsonOem,
    SensitivusGauge,
    Shapelog,
    Sigmasport,
    SoaringTechnology,
    SoundOfMotion,
    Spantec,
    SparkHk,
    Specialized,
    Spivi,
    Sram,
    Srm,
    StagesCycling,
    StarTrac,
    Strava,
    Stryd,
    Suunto,
    Tacx,
    Tanita,
    Technogym,
    TheHurtBox,
    TheSufferfest,
    Thinkrider,
    ThitaElektronik,
    Tigrasport,
    Timex,
    Tomtom,
    TopactionTechnology,
    TrainerRoad,
    Vdo,
    Velosense,
    Virtualtraining,
    Virtugo,
    WahooFitness,
    Waterrower,
    Wattbike,
    Watteam,
    Wellgo,
    Woodway,
    Wtek,
    Xelic,
    Xplova,
    Zephyr,
    Zwift,
    UnknownValue(u64),
}

impl From<FieldContent> for Manufacturer {
    fn from(field: FieldContent) -> Self {
        if let FieldContent::UnsignedInt16(enum_value) = field {
            match enum_value {
                1 => Manufacturer::Garmin,
                2 => Manufacturer::GarminFr405Antfs,
                3 => Manufacturer::Zephyr,
                4 => Manufacturer::Dayton,
                5 => Manufacturer::Idt,
                6 => Manufacturer::Srm,
                7 => Manufacturer::Quarq,
                8 => Manufacturer::Ibike,
                9 => Manufacturer::Saris,
                10 => Manufacturer::SparkHk,
                11 => Manufacturer::Tanita,
                12 => Manufacturer::Echowell,
                13 => Manufacturer::DynastreamOem,
                14 => Manufacturer::Nautilus,
                15 => Manufacturer::Dynastream,
                16 => Manufacturer::Timex,
                17 => Manufacturer::Metrigear,
                18 => Manufacturer::Xelic,
                19 => Manufacturer::Beurer,
                20 => Manufacturer::Cardiosport,
                21 => Manufacturer::AAndD,
                22 => Manufacturer::Hmm,
                23 => Manufacturer::Suunto,
                24 => Manufacturer::ThitaElektronik,
                25 => Manufacturer::Gpulse,
                26 => Manufacturer::CleanMobile,
                27 => Manufacturer::PedalBrain,
                28 => Manufacturer::Peaksware,
                29 => Manufacturer::Saxonar,
                30 => Manufacturer::LemondFitness,
                31 => Manufacturer::Dexcom,
                32 => Manufacturer::WahooFitness,
                33 => Manufacturer::OctaneFitness,
                34 => Manufacturer::Archinoetics,
                35 => Manufacturer::TheHurtBox,
                36 => Manufacturer::CitizenSystems,
                37 => Manufacturer::Magellan,
                38 => Manufacturer::Osynce,
                39 => Manufacturer::Holux,
                40 => Manufacturer::Concept2,
                42 => Manufacturer::OneGiantLeap,
                43 => Manufacturer::AceSensor,
                44 => Manufacturer::BrimBrothers,
                45 => Manufacturer::Xplova,
                46 => Manufacturer::PerceptionDigital,
                47 => Manufacturer::Bf1Systems,
                48 => Manufacturer::Pioneer,
                49 => Manufacturer::Spantec,
                50 => Manufacturer::Metalogics,
                51 => Manufacturer::FourIIIIs,
                52 => Manufacturer::SeikoEpson,
                53 => Manufacturer::SeikoEpsonOem,
                54 => Manufacturer::IforPowell,
                55 => Manufacturer::MaxwellGuider,
                56 => Manufacturer::StarTrac,
                57 => Manufacturer::Breakaway,
                58 => Manufacturer::AlatechTechnologyLtd,
                59 => Manufacturer::MioTechnologyEurope,
                60 => Manufacturer::Rotor,
                61 => Manufacturer::Geonaute,
                62 => Manufacturer::IdBike,
                63 => Manufacturer::Specialized,
                64 => Manufacturer::Wtek,
                65 => Manufacturer::PhysicalEnterprises,
                66 => Manufacturer::NorthPoleEngineering,
                67 => Manufacturer::Bkool,
                68 => Manufacturer::Cateye,
                69 => Manufacturer::StagesCycling,
                70 => Manufacturer::Sigmasport,
                71 => Manufacturer::Tomtom,
                72 => Manufacturer::Peripedal,
                73 => Manufacturer::Wattbike,
                76 => Manufacturer::Moxy,
                77 => Manufacturer::Ciclosport,
                78 => Manufacturer::Powerbahn,
                79 => Manufacturer::AcornProjectsAps,
                80 => Manufacturer::Lifebeam,
                81 => Manufacturer::Bontrager,
                82 => Manufacturer::Wellgo,
                83 => Manufacturer::Scosche,
                84 => Manufacturer::Magura,
                85 => Manufacturer::Woodway,
                86 => Manufacturer::Elite,
                87 => Manufacturer::NielsenKellerman,
                88 => Manufacturer::DkCity,
                89 => Manufacturer::Tacx,
                90 => Manufacturer::DirectionTechnology,
                91 => Manufacturer::Magtonic,
                92 => Manufacturer::OnePartCarbon,
                93 => Manufacturer::InsideRideTechnologies,
                94 => Manufacturer::SoundOfMotion,
                95 => Manufacturer::Stryd,
                96 => Manufacturer::Icg,
                97 => Manufacturer::MiPulse,
                98 => Manufacturer::BsxAthletics,
                99 => Manufacturer::Look,
                100 => Manufacturer::CampagnoloSrl,
                101 => Manufacturer::BodyBikeSmart,
                102 => Manufacturer::Praxisworks,
                103 => Manufacturer::LimitsTechnology,
                104 => Manufacturer::TopactionTechnology,
                105 => Manufacturer::Cosinuss,
                106 => Manufacturer::Fitcare,
                107 => Manufacturer::Magene,
                108 => Manufacturer::GiantManufacturingCo,
                109 => Manufacturer::Tigrasport,
                110 => Manufacturer::Salutron,
                111 => Manufacturer::Technogym,
                112 => Manufacturer::BrytonSensors,
                113 => Manufacturer::LatitudeLimited,
                114 => Manufacturer::SoaringTechnology,
                115 => Manufacturer::Igpsport,
                116 => Manufacturer::Thinkrider,
                117 => Manufacturer::GopherSport,
                118 => Manufacturer::Waterrower,
                119 => Manufacturer::Orangetheory,
                120 => Manufacturer::Inpeak,
                121 => Manufacturer::Kinetic,
                122 => Manufacturer::JohnsonHealthTech,
                123 => Manufacturer::PolarElectro,
                124 => Manufacturer::Seesense,
                125 => Manufacturer::NciTechnology,
                255 => Manufacturer::Development,
                257 => Manufacturer::Healthandlife,
                258 => Manufacturer::Lezyne,
                259 => Manufacturer::ScribeLabs,
                260 => Manufacturer::Zwift,
                261 => Manufacturer::Watteam,
                262 => Manufacturer::Recon,
                263 => Manufacturer::FaveroElectronics,
                264 => Manufacturer::Dynovelo,
                265 => Manufacturer::Strava,
                266 => Manufacturer::Precor,
                267 => Manufacturer::Bryton,
                268 => Manufacturer::Sram,
                269 => Manufacturer::Navman,
                270 => Manufacturer::Cobi,
                271 => Manufacturer::Spivi,
                272 => Manufacturer::MioMagellan,
                273 => Manufacturer::Evesports,
                274 => Manufacturer::SensitivusGauge,
                275 => Manufacturer::Podoon,
                276 => Manufacturer::LifeTimeFitness,
                277 => Manufacturer::FalcoEMotors,
                278 => Manufacturer::Minoura,
                279 => Manufacturer::Cycliq,
                280 => Manufacturer::Luxottica,
                281 => Manufacturer::TrainerRoad,
                282 => Manufacturer::TheSufferfest,
                283 => Manufacturer::Fullspeedahead,
                284 => Manufacturer::Virtualtraining,
                285 => Manufacturer::Feedbacksports,
                286 => Manufacturer::Omata,
                287 => Manufacturer::Vdo,
                288 => Manufacturer::Magneticdays,
                289 => Manufacturer::Hammerhead,
                290 => Manufacturer::KineticByKurt,
                291 => Manufacturer::Shapelog,
                292 => Manufacturer::Dabuziduo,
                293 => Manufacturer::Jetblack,
                294 => Manufacturer::Coros,
                295 => Manufacturer::Virtugo,
                296 => Manufacturer::Velosense,
                297 => Manufacturer::Cycligentinc,
                5759 => Manufacturer::Actigraphcorp,
                n => Manufacturer::UnknownValue(n as u64),
            }
        } else {
          panic!("can't convert Manufacturer to {:?}", field);
        }
    }
}
