use crate::fields::FieldContent;
use serde::Serialize;

#[derive(Clone, Copy, Debug, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum MesgNum {
    AccelerometerData,
    Activity,
    AntChannelId,
    AntRx,
    AntTx,
    AviationAttitude,
    BarometerData,
    BikeProfile,
    BloodPressure,
    CadenceZone,
    CameraEvent,
    Capabilities,
    Connectivity,
    Course,
    CoursePoint,
    DeveloperDataId,
    DeviceInfo,
    DeviceSettings,
    DiveAlarm,
    DiveGas,
    DiveSettings,
    DiveSummary,
    Event,
    ExdDataConceptConfiguration,
    ExdDataFieldConfiguration,
    ExdScreenConfiguration,
    ExerciseTitle,
    FieldCapabilities,
    FieldDescription,
    FileCapabilities,
    FileCreator,
    FileId,
    Goal,
    GpsMetadata,
    GyroscopeData,
    Hr,
    HrZone,
    HrmProfile,
    Hrv,
    Lap,
    Length,
    MagnetometerData,
    MemoGlob,
    MesgCapabilities,
    MetZone,
    Monitoring,
    MonitoringInfo,
    NmeaSentence,
    ObdiiData,
    OhrSettings,
    OneDSensorCalibration,
    Pad,
    PowerZone,
    Record,
    Schedule,
    SdmProfile,
    SegmentFile,
    SegmentId,
    SegmentLap,
    SegmentLeaderboardEntry,
    SegmentPoint,
    Session,
    Set,
    SlaveDevice,
    Software,
    SpeedZone,
    Sport,
    StressLevel,
    ThreeDSensorCalibration,
    TimestampCorrelation,
    Totals,
    TrainingFile,
    UserProfile,
    Video,
    VideoClip,
    VideoDescription,
    VideoFrame,
    VideoTitle,
    WatchfaceSettings,
    WeatherAlert,
    WeatherConditions,
    WeightScale,
    Workout,
    WorkoutSession,
    WorkoutStep,
    ZonesTarget,
    UnknownValue(u64),
}

impl From<FieldContent> for MesgNum {
    fn from(field: FieldContent) -> Self {
        if let FieldContent::UnsignedInt16(enum_value) = field {
            match enum_value {
                0 => MesgNum::FileId,
                1 => MesgNum::Capabilities,
                2 => MesgNum::DeviceSettings,
                3 => MesgNum::UserProfile,
                4 => MesgNum::HrmProfile,
                5 => MesgNum::SdmProfile,
                6 => MesgNum::BikeProfile,
                7 => MesgNum::ZonesTarget,
                8 => MesgNum::HrZone,
                9 => MesgNum::PowerZone,
                10 => MesgNum::MetZone,
                12 => MesgNum::Sport,
                15 => MesgNum::Goal,
                18 => MesgNum::Session,
                19 => MesgNum::Lap,
                20 => MesgNum::Record,
                21 => MesgNum::Event,
                23 => MesgNum::DeviceInfo,
                26 => MesgNum::Workout,
                27 => MesgNum::WorkoutStep,
                28 => MesgNum::Schedule,
                30 => MesgNum::WeightScale,
                31 => MesgNum::Course,
                32 => MesgNum::CoursePoint,
                33 => MesgNum::Totals,
                34 => MesgNum::Activity,
                35 => MesgNum::Software,
                37 => MesgNum::FileCapabilities,
                38 => MesgNum::MesgCapabilities,
                39 => MesgNum::FieldCapabilities,
                49 => MesgNum::FileCreator,
                51 => MesgNum::BloodPressure,
                53 => MesgNum::SpeedZone,
                55 => MesgNum::Monitoring,
                72 => MesgNum::TrainingFile,
                78 => MesgNum::Hrv,
                80 => MesgNum::AntRx,
                81 => MesgNum::AntTx,
                82 => MesgNum::AntChannelId,
                101 => MesgNum::Length,
                103 => MesgNum::MonitoringInfo,
                105 => MesgNum::Pad,
                106 => MesgNum::SlaveDevice,
                127 => MesgNum::Connectivity,
                128 => MesgNum::WeatherConditions,
                129 => MesgNum::WeatherAlert,
                131 => MesgNum::CadenceZone,
                132 => MesgNum::Hr,
                142 => MesgNum::SegmentLap,
                145 => MesgNum::MemoGlob,
                148 => MesgNum::SegmentId,
                149 => MesgNum::SegmentLeaderboardEntry,
                150 => MesgNum::SegmentPoint,
                151 => MesgNum::SegmentFile,
                158 => MesgNum::WorkoutSession,
                159 => MesgNum::WatchfaceSettings,
                160 => MesgNum::GpsMetadata,
                161 => MesgNum::CameraEvent,
                162 => MesgNum::TimestampCorrelation,
                164 => MesgNum::GyroscopeData,
                165 => MesgNum::AccelerometerData,
                167 => MesgNum::ThreeDSensorCalibration,
                169 => MesgNum::VideoFrame,
                174 => MesgNum::ObdiiData,
                177 => MesgNum::NmeaSentence,
                178 => MesgNum::AviationAttitude,
                184 => MesgNum::Video,
                185 => MesgNum::VideoTitle,
                186 => MesgNum::VideoDescription,
                187 => MesgNum::VideoClip,
                188 => MesgNum::OhrSettings,
                200 => MesgNum::ExdScreenConfiguration,
                201 => MesgNum::ExdDataFieldConfiguration,
                202 => MesgNum::ExdDataConceptConfiguration,
                206 => MesgNum::FieldDescription,
                207 => MesgNum::DeveloperDataId,
                208 => MesgNum::MagnetometerData,
                209 => MesgNum::BarometerData,
                210 => MesgNum::OneDSensorCalibration,
                225 => MesgNum::Set,
                227 => MesgNum::StressLevel,
                258 => MesgNum::DiveSettings,
                259 => MesgNum::DiveGas,
                262 => MesgNum::DiveAlarm,
                264 => MesgNum::ExerciseTitle,
                268 => MesgNum::DiveSummary,
                n => MesgNum::UnknownValue(n as u64),
            }
        } else {
          panic!("can't convert MesgNum to {:?}", field);
        }
    }
}
