// DO NOT EDIT -- generated code

mod activity;
mod activity_class;
mod activity_level;
mod activity_subtype;
mod activity_type;
mod analog_watchface_layout;
mod ant_network;
mod antplus_device_type;
mod attitude_stage;
mod attitude_validity;
mod auto_activity_detect;
mod auto_sync_frequency;
mod autolap_trigger;
mod autoscroll;
mod backlight_mode;
mod backlight_timeout;
mod battery_status;
mod bench_press_exercise_name;
mod bike_light_beam_angle_mode;
mod bike_light_network_config_type;
mod body_location;
mod bp_status;
mod calf_raise_exercise_name;
mod camera_event_type;
mod camera_orientation_type;
mod cardio_exercise_name;
mod carry_exercise_name;
mod checksum;
mod chop_exercise_name;
mod comm_timeout_type;
mod connectivity_capabilities;
mod core_exercise_name;
mod course_capabilities;
mod course_point;
mod crunch_exercise_name;
mod curl_exercise_name;
mod date_mode;
mod date_time;
mod day_of_week;
mod deadlift_exercise_name;
mod device_index;
mod digital_watchface_layout;
mod display_heart;
mod display_measure;
mod display_orientation;
mod display_position;
mod display_power;
mod dive_alarm_type;
mod dive_backlight_mode;
mod dive_gas_status;
mod event;
mod event_type;
mod exd_data_units;
mod exd_descriptors;
mod exd_display_type;
mod exd_layout;
mod exd_qualifiers;
mod exercise_category;
mod favero_product;
mod file;
mod file_flags;
mod fit_base_type;
mod fit_base_unit;
mod fitness_equipment_state;
mod flye_exercise_name;
mod garmin_product;
mod gender;
mod goal;
mod goal_recurrence;
mod goal_source;
mod hip_raise_exercise_name;
mod hip_stability_exercise_name;
mod hip_swing_exercise_name;
mod hr_type;
mod hr_zone_calc;
mod hyperextension_exercise_name;
mod intensity;
mod language;
mod lap_trigger;
mod lateral_raise_exercise_name;
mod left_right_balance;
mod left_right_balance_100;
mod leg_curl_exercise_name;
mod leg_raise_exercise_name;
mod length_type;
mod local_date_time;
mod local_device_type;
mod localtime_into_day;
mod lunge_exercise_name;
mod manufacturer;
mod mesg_count;
mod mesg_num;
mod message_index;
mod olympic_lift_exercise_name;
mod plank_exercise_name;
mod plyo_exercise_name;
mod power_phase_type;
mod pull_up_exercise_name;
mod push_up_exercise_name;
mod pwr_zone_calc;
mod rider_position_type;
mod row_exercise_name;
mod run_exercise_name;
mod schedule;
mod segment_delete_status;
mod segment_lap_status;
mod segment_leaderboard_type;
mod segment_selection_type;
mod sensor_type;
mod session_trigger;
mod set_type;
mod shoulder_press_exercise_name;
mod shoulder_stability_exercise_name;
mod shrug_exercise_name;
mod side;
mod sit_up_exercise_name;
mod source_type;
mod sport;
mod sport_event;
mod squat_exercise_name;
mod stroke_type;
mod sub_sport;
mod supported_exd_screen_layouts;
mod swim_stroke;
mod switch;
mod time_into_day;
mod time_mode;
mod time_zone;
mod timer_trigger;
mod tissue_model_type;
mod tone;
mod total_body_exercise_name;
mod triceps_extension_exercise_name;
mod turn_type;
mod user_local_id;
mod warm_up_exercise_name;
mod watchface_mode;
mod water_type;
mod weather_report;
mod weather_severe_type;
mod weather_severity;
mod weather_status;
mod weight;
mod wkt_step_duration;
mod wkt_step_target;
mod workout_capabilities;
mod workout_equipment;
mod workout_hr;
mod workout_power;

pub use self::activity::Activity;
pub use self::activity_class::ActivityClass;
pub use self::activity_level::ActivityLevel;
pub use self::activity_subtype::ActivitySubtype;
pub use self::activity_type::ActivityType;
pub use self::analog_watchface_layout::AnalogWatchfaceLayout;
pub use self::ant_network::AntNetwork;
pub use self::antplus_device_type::AntplusDeviceType;
pub use self::attitude_stage::AttitudeStage;
pub use self::attitude_validity::AttitudeValidity;
pub use self::auto_activity_detect::AutoActivityDetect;
pub use self::auto_sync_frequency::AutoSyncFrequency;
pub use self::autolap_trigger::AutolapTrigger;
pub use self::autoscroll::Autoscroll;
pub use self::backlight_mode::BacklightMode;
pub use self::backlight_timeout::BacklightTimeout;
pub use self::battery_status::BatteryStatus;
pub use self::bench_press_exercise_name::BenchPressExerciseName;
pub use self::bike_light_beam_angle_mode::BikeLightBeamAngleMode;
pub use self::bike_light_network_config_type::BikeLightNetworkConfigType;
pub use self::body_location::BodyLocation;
pub use self::bp_status::BpStatus;
pub use self::calf_raise_exercise_name::CalfRaiseExerciseName;
pub use self::camera_event_type::CameraEventType;
pub use self::camera_orientation_type::CameraOrientationType;
pub use self::cardio_exercise_name::CardioExerciseName;
pub use self::carry_exercise_name::CarryExerciseName;
pub use self::checksum::Checksum;
pub use self::chop_exercise_name::ChopExerciseName;
pub use self::comm_timeout_type::CommTimeoutType;
pub use self::connectivity_capabilities::ConnectivityCapabilities;
pub use self::core_exercise_name::CoreExerciseName;
pub use self::course_capabilities::CourseCapabilities;
pub use self::course_point::CoursePoint;
pub use self::crunch_exercise_name::CrunchExerciseName;
pub use self::curl_exercise_name::CurlExerciseName;
pub use self::date_mode::DateMode;
pub use self::date_time::DateTime;
pub use self::day_of_week::DayOfWeek;
pub use self::deadlift_exercise_name::DeadliftExerciseName;
pub use self::device_index::DeviceIndex;
pub use self::digital_watchface_layout::DigitalWatchfaceLayout;
pub use self::display_heart::DisplayHeart;
pub use self::display_measure::DisplayMeasure;
pub use self::display_orientation::DisplayOrientation;
pub use self::display_position::DisplayPosition;
pub use self::display_power::DisplayPower;
pub use self::dive_alarm_type::DiveAlarmType;
pub use self::dive_backlight_mode::DiveBacklightMode;
pub use self::dive_gas_status::DiveGasStatus;
pub use self::event::Event;
pub use self::event_type::EventType;
pub use self::exd_data_units::ExdDataUnits;
pub use self::exd_descriptors::ExdDescriptors;
pub use self::exd_display_type::ExdDisplayType;
pub use self::exd_layout::ExdLayout;
pub use self::exd_qualifiers::ExdQualifiers;
pub use self::exercise_category::ExerciseCategory;
pub use self::favero_product::FaveroProduct;
pub use self::file::File;
pub use self::file_flags::FileFlags;
pub use self::fit_base_type::FitBaseType;
pub use self::fit_base_unit::FitBaseUnit;
pub use self::fitness_equipment_state::FitnessEquipmentState;
pub use self::flye_exercise_name::FlyeExerciseName;
pub use self::garmin_product::GarminProduct;
pub use self::gender::Gender;
pub use self::goal::Goal;
pub use self::goal_recurrence::GoalRecurrence;
pub use self::goal_source::GoalSource;
pub use self::hip_raise_exercise_name::HipRaiseExerciseName;
pub use self::hip_stability_exercise_name::HipStabilityExerciseName;
pub use self::hip_swing_exercise_name::HipSwingExerciseName;
pub use self::hr_type::HrType;
pub use self::hr_zone_calc::HrZoneCalc;
pub use self::hyperextension_exercise_name::HyperextensionExerciseName;
pub use self::intensity::Intensity;
pub use self::language::Language;
pub use self::lap_trigger::LapTrigger;
pub use self::lateral_raise_exercise_name::LateralRaiseExerciseName;
pub use self::left_right_balance::LeftRightBalance;
pub use self::left_right_balance_100::LeftRightBalance100;
pub use self::leg_curl_exercise_name::LegCurlExerciseName;
pub use self::leg_raise_exercise_name::LegRaiseExerciseName;
pub use self::length_type::LengthType;
pub use self::local_date_time::LocalDateTime;
pub use self::local_device_type::LocalDeviceType;
pub use self::localtime_into_day::LocaltimeIntoDay;
pub use self::lunge_exercise_name::LungeExerciseName;
pub use self::manufacturer::Manufacturer;
pub use self::mesg_count::MesgCount;
pub use self::mesg_num::MesgNum;
pub use self::message_index::MessageIndex;
pub use self::olympic_lift_exercise_name::OlympicLiftExerciseName;
pub use self::plank_exercise_name::PlankExerciseName;
pub use self::plyo_exercise_name::PlyoExerciseName;
pub use self::power_phase_type::PowerPhaseType;
pub use self::pull_up_exercise_name::PullUpExerciseName;
pub use self::push_up_exercise_name::PushUpExerciseName;
pub use self::pwr_zone_calc::PwrZoneCalc;
pub use self::rider_position_type::RiderPositionType;
pub use self::row_exercise_name::RowExerciseName;
pub use self::run_exercise_name::RunExerciseName;
pub use self::schedule::Schedule;
pub use self::segment_delete_status::SegmentDeleteStatus;
pub use self::segment_lap_status::SegmentLapStatus;
pub use self::segment_leaderboard_type::SegmentLeaderboardType;
pub use self::segment_selection_type::SegmentSelectionType;
pub use self::sensor_type::SensorType;
pub use self::session_trigger::SessionTrigger;
pub use self::set_type::SetType;
pub use self::shoulder_press_exercise_name::ShoulderPressExerciseName;
pub use self::shoulder_stability_exercise_name::ShoulderStabilityExerciseName;
pub use self::shrug_exercise_name::ShrugExerciseName;
pub use self::side::Side;
pub use self::sit_up_exercise_name::SitUpExerciseName;
pub use self::source_type::SourceType;
pub use self::sport::Sport;
pub use self::sport_event::SportEvent;
pub use self::squat_exercise_name::SquatExerciseName;
pub use self::stroke_type::StrokeType;
pub use self::sub_sport::SubSport;
pub use self::supported_exd_screen_layouts::SupportedExdScreenLayouts;
pub use self::swim_stroke::SwimStroke;
pub use self::switch::Switch;
pub use self::time_into_day::TimeIntoDay;
pub use self::time_mode::TimeMode;
pub use self::time_zone::TimeZone;
pub use self::timer_trigger::TimerTrigger;
pub use self::tissue_model_type::TissueModelType;
pub use self::tone::Tone;
pub use self::total_body_exercise_name::TotalBodyExerciseName;
pub use self::triceps_extension_exercise_name::TricepsExtensionExerciseName;
pub use self::turn_type::TurnType;
pub use self::user_local_id::UserLocalId;
pub use self::warm_up_exercise_name::WarmUpExerciseName;
pub use self::watchface_mode::WatchfaceMode;
pub use self::water_type::WaterType;
pub use self::weather_report::WeatherReport;
pub use self::weather_severe_type::WeatherSevereType;
pub use self::weather_severity::WeatherSeverity;
pub use self::weather_status::WeatherStatus;
pub use self::weight::Weight;
pub use self::wkt_step_duration::WktStepDuration;
pub use self::wkt_step_target::WktStepTarget;
pub use self::workout_capabilities::WorkoutCapabilities;
pub use self::workout_equipment::WorkoutEquipment;
pub use self::workout_hr::WorkoutHr;
pub use self::workout_power::WorkoutPower;
