use crate::fields::FieldContent;
use serde::Serialize;

#[derive(Clone, Copy, Debug, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum Sport {
    All,
    AlpineSkiing,
    AmericanFootball,
    Basketball,
    Boating,
    Boxing,
    CrossCountrySkiing,
    Cycling,
    Driving,
    EBiking,
    Fishing,
    FitnessEquipment,
    FloorClimbing,
    Flying,
    Generic,
    Golf,
    HangGliding,
    Hiking,
    HorsebackRiding,
    Hunting,
    IceSkating,
    InlineSkating,
    Jumpmaster,
    Kayaking,
    Kitesurfing,
    Motorcycling,
    Mountaineering,
    Multisport,
    Paddling,
    Rafting,
    RockClimbing,
    Rowing,
    Running,
    Sailing,
    SkyDiving,
    Snowboarding,
    Snowmobiling,
    Snowshoeing,
    Soccer,
    StandUpPaddleboarding,
    Surfing,
    Swimming,
    Tactical,
    Tennis,
    Training,
    Transition,
    Wakeboarding,
    Walking,
    WaterSkiing,
    Windsurfing,
    UnknownValue(u64),
}

impl From<FieldContent> for Sport {
    fn from(field: FieldContent) -> Self {
        if let FieldContent::Enum(enum_value) = field {
            match enum_value {
                0 => Sport::Generic,
                1 => Sport::Running,
                2 => Sport::Cycling,
                3 => Sport::Transition,
                4 => Sport::FitnessEquipment,
                5 => Sport::Swimming,
                6 => Sport::Basketball,
                7 => Sport::Soccer,
                8 => Sport::Tennis,
                9 => Sport::AmericanFootball,
                10 => Sport::Training,
                11 => Sport::Walking,
                12 => Sport::CrossCountrySkiing,
                13 => Sport::AlpineSkiing,
                14 => Sport::Snowboarding,
                15 => Sport::Rowing,
                16 => Sport::Mountaineering,
                17 => Sport::Hiking,
                18 => Sport::Multisport,
                19 => Sport::Paddling,
                20 => Sport::Flying,
                21 => Sport::EBiking,
                22 => Sport::Motorcycling,
                23 => Sport::Boating,
                24 => Sport::Driving,
                25 => Sport::Golf,
                26 => Sport::HangGliding,
                27 => Sport::HorsebackRiding,
                28 => Sport::Hunting,
                29 => Sport::Fishing,
                30 => Sport::InlineSkating,
                31 => Sport::RockClimbing,
                32 => Sport::Sailing,
                33 => Sport::IceSkating,
                34 => Sport::SkyDiving,
                35 => Sport::Snowshoeing,
                36 => Sport::Snowmobiling,
                37 => Sport::StandUpPaddleboarding,
                38 => Sport::Surfing,
                39 => Sport::Wakeboarding,
                40 => Sport::WaterSkiing,
                41 => Sport::Kayaking,
                42 => Sport::Rafting,
                43 => Sport::Windsurfing,
                44 => Sport::Kitesurfing,
                45 => Sport::Tactical,
                46 => Sport::Jumpmaster,
                47 => Sport::Boxing,
                48 => Sport::FloorClimbing,
                254 => Sport::All,
                n => Sport::UnknownValue(n as u64),
            }
        } else {
          panic!("can't convert Sport to {:?}", field);
        }
    }
}
