use crate::fields::FieldContent;
use serde::Serialize;

#[derive(Clone, Copy, Debug, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum SquatExerciseName {
    BackSquatWithBodyBar,
    BackSquats,
    BalancingSquat,
    BarbellBackSquat,
    BarbellBoxSquat,
    BarbellFrontSquat,
    BarbellHackSquat,
    BarbellHangSquatSnatch,
    BarbellLateralStepUp,
    BarbellQuarterSquat,
    BarbellSiffSquat,
    BarbellSquatSnatch,
    BarbellSquatWithHeelsRaised,
    BarbellStepUp,
    BarbellStepover,
    BenchSquatWithRotationalChop,
    BodyWeightWallSquat,
    BoxStepSquat,
    BracedSquat,
    CrossedArmBarbellFrontSquat,
    CrossoverDumbbellStepUp,
    DumbbellFrontSquat,
    DumbbellSplitSquat,
    DumbbellSquat,
    DumbbellSquatClean,
    DumbbellStepUp,
    DumbbellStepover,
    ElevatedSingleLegSquat,
    FigureFourSquats,
    GobletSquat,
    KbsOverhead,
    KettlebellSquat,
    KettlebellSwingOverhead,
    KettlebellSwingWithFlipToSquat,
    LateralDumbbellStepUp,
    LegPress,
    OneLeggedSquat,
    OverheadDumbbellSquat,
    OverheadSquat,
    PartialSingleLegSquat,
    PilatesPlieSquatsParallelTurnedOutFlatAndHeels,
    PistolSquat,
    PlieSlides,
    PlieSquat,
    PrisonerSquat,
    ReleveStraightLegAndKneeBentWithOneLegVariation,
    SingleLegBenchGetUp,
    SingleLegBenchSquat,
    SingleLegSquatOnSwissBall,
    Squat,
    SquatAndSideKick,
    SquatJumpsInNOut,
    SquatsWithBand,
    StaggeredSquat,
    StepUp,
    SuitcaseSquats,
    SumoSquat,
    SumoSquatSlideIn,
    SumoSquatToHighPull,
    SumoSquatToStand,
    SumoSquatWithRotation,
    SwissBallBodyWeightWallSquat,
    Thrusters,
    UnevenSquat,
    WaistSlimmingSquat,
    WallBall,
    WeightedBackSquats,
    WeightedBalancingSquat,
    WeightedBenchSquatWithRotationalChop,
    WeightedBoxStepSquat,
    WeightedElevatedSingleLegSquat,
    WeightedFigureFourSquats,
    WeightedPartialSingleLegSquat,
    WeightedPistolSquat,
    WeightedPlieSlides,
    WeightedPlieSquat,
    WeightedPrisonerSquat,
    WeightedSingleLegBenchGetUp,
    WeightedSingleLegBenchSquat,
    WeightedSingleLegSquatOnSwissBall,
    WeightedSquat,
    WeightedStaggeredSquat,
    WeightedStepUp,
    WeightedSumoSquatSlideIn,
    WeightedSumoSquatToStand,
    WeightedSumoSquatWithRotation,
    WeightedSwissBallWallSquat,
    WeightedUnevenSquat,
    WeightedWallSquat,
    WideStanceBarbellSquat,
    WideStanceGobletSquat,
    ZercherSquat,
    UnknownValue(u64),
}

impl From<FieldContent> for SquatExerciseName {
    fn from(field: FieldContent) -> Self {
        if let FieldContent::UnsignedInt16(enum_value) = field {
            match enum_value {
                0 => SquatExerciseName::LegPress,
                1 => SquatExerciseName::BackSquatWithBodyBar,
                2 => SquatExerciseName::BackSquats,
                3 => SquatExerciseName::WeightedBackSquats,
                4 => SquatExerciseName::BalancingSquat,
                5 => SquatExerciseName::WeightedBalancingSquat,
                6 => SquatExerciseName::BarbellBackSquat,
                7 => SquatExerciseName::BarbellBoxSquat,
                8 => SquatExerciseName::BarbellFrontSquat,
                9 => SquatExerciseName::BarbellHackSquat,
                10 => SquatExerciseName::BarbellHangSquatSnatch,
                11 => SquatExerciseName::BarbellLateralStepUp,
                12 => SquatExerciseName::BarbellQuarterSquat,
                13 => SquatExerciseName::BarbellSiffSquat,
                14 => SquatExerciseName::BarbellSquatSnatch,
                15 => SquatExerciseName::BarbellSquatWithHeelsRaised,
                16 => SquatExerciseName::BarbellStepover,
                17 => SquatExerciseName::BarbellStepUp,
                18 => SquatExerciseName::BenchSquatWithRotationalChop,
                19 => SquatExerciseName::WeightedBenchSquatWithRotationalChop,
                20 => SquatExerciseName::BodyWeightWallSquat,
                21 => SquatExerciseName::WeightedWallSquat,
                22 => SquatExerciseName::BoxStepSquat,
                23 => SquatExerciseName::WeightedBoxStepSquat,
                24 => SquatExerciseName::BracedSquat,
                25 => SquatExerciseName::CrossedArmBarbellFrontSquat,
                26 => SquatExerciseName::CrossoverDumbbellStepUp,
                27 => SquatExerciseName::DumbbellFrontSquat,
                28 => SquatExerciseName::DumbbellSplitSquat,
                29 => SquatExerciseName::DumbbellSquat,
                30 => SquatExerciseName::DumbbellSquatClean,
                31 => SquatExerciseName::DumbbellStepover,
                32 => SquatExerciseName::DumbbellStepUp,
                33 => SquatExerciseName::ElevatedSingleLegSquat,
                34 => SquatExerciseName::WeightedElevatedSingleLegSquat,
                35 => SquatExerciseName::FigureFourSquats,
                36 => SquatExerciseName::WeightedFigureFourSquats,
                37 => SquatExerciseName::GobletSquat,
                38 => SquatExerciseName::KettlebellSquat,
                39 => SquatExerciseName::KettlebellSwingOverhead,
                40 => SquatExerciseName::KettlebellSwingWithFlipToSquat,
                41 => SquatExerciseName::LateralDumbbellStepUp,
                42 => SquatExerciseName::OneLeggedSquat,
                43 => SquatExerciseName::OverheadDumbbellSquat,
                44 => SquatExerciseName::OverheadSquat,
                45 => SquatExerciseName::PartialSingleLegSquat,
                46 => SquatExerciseName::WeightedPartialSingleLegSquat,
                47 => SquatExerciseName::PistolSquat,
                48 => SquatExerciseName::WeightedPistolSquat,
                49 => SquatExerciseName::PlieSlides,
                50 => SquatExerciseName::WeightedPlieSlides,
                51 => SquatExerciseName::PlieSquat,
                52 => SquatExerciseName::WeightedPlieSquat,
                53 => SquatExerciseName::PrisonerSquat,
                54 => SquatExerciseName::WeightedPrisonerSquat,
                55 => SquatExerciseName::SingleLegBenchGetUp,
                56 => SquatExerciseName::WeightedSingleLegBenchGetUp,
                57 => SquatExerciseName::SingleLegBenchSquat,
                58 => SquatExerciseName::WeightedSingleLegBenchSquat,
                59 => SquatExerciseName::SingleLegSquatOnSwissBall,
                60 => SquatExerciseName::WeightedSingleLegSquatOnSwissBall,
                61 => SquatExerciseName::Squat,
                62 => SquatExerciseName::WeightedSquat,
                63 => SquatExerciseName::SquatsWithBand,
                64 => SquatExerciseName::StaggeredSquat,
                65 => SquatExerciseName::WeightedStaggeredSquat,
                66 => SquatExerciseName::StepUp,
                67 => SquatExerciseName::WeightedStepUp,
                68 => SquatExerciseName::SuitcaseSquats,
                69 => SquatExerciseName::SumoSquat,
                70 => SquatExerciseName::SumoSquatSlideIn,
                71 => SquatExerciseName::WeightedSumoSquatSlideIn,
                72 => SquatExerciseName::SumoSquatToHighPull,
                73 => SquatExerciseName::SumoSquatToStand,
                74 => SquatExerciseName::WeightedSumoSquatToStand,
                75 => SquatExerciseName::SumoSquatWithRotation,
                76 => SquatExerciseName::WeightedSumoSquatWithRotation,
                77 => SquatExerciseName::SwissBallBodyWeightWallSquat,
                78 => SquatExerciseName::WeightedSwissBallWallSquat,
                79 => SquatExerciseName::Thrusters,
                80 => SquatExerciseName::UnevenSquat,
                81 => SquatExerciseName::WeightedUnevenSquat,
                82 => SquatExerciseName::WaistSlimmingSquat,
                83 => SquatExerciseName::WallBall,
                84 => SquatExerciseName::WideStanceBarbellSquat,
                85 => SquatExerciseName::WideStanceGobletSquat,
                86 => SquatExerciseName::ZercherSquat,
                87 => SquatExerciseName::KbsOverhead,
                88 => SquatExerciseName::SquatAndSideKick,
                89 => SquatExerciseName::SquatJumpsInNOut,
                90 => SquatExerciseName::PilatesPlieSquatsParallelTurnedOutFlatAndHeels,
                91 => SquatExerciseName::ReleveStraightLegAndKneeBentWithOneLegVariation,
                n => SquatExerciseName::UnknownValue(n as u64),
            }
        } else {
          panic!("can't convert SquatExerciseName to {:?}", field);
        }
    }
}
