use crate::fields::FieldContent;
use serde::Serialize;

#[derive(Clone, Copy, Debug, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum TricepsExtensionExerciseName {
    BenchDip,
    BodyWeightDip,
    CableKickback,
    CableLyingTricepsExtension,
    CableOverheadTricepsExtension,
    DumbbellKickback,
    DumbbellLyingTricepsExtension,
    EzBarOverheadTricepsExtension,
    InclineDip,
    InclineEzBarLyingTricepsExtension,
    LyingDumbbellPulloverToExtension,
    LyingEzBarTricepsExtension,
    LyingTricepsExtensionToCloseGripBenchPress,
    OverheadDumbbellTricepsExtension,
    RecliningTricepsPress,
    ReverseGripPressdown,
    ReverseGripTricepsPressdown,
    RopePressdown,
    SeatedBarbellOverheadTricepsExtension,
    SeatedDumbbellOverheadTricepsExtension,
    SeatedEzBarOverheadTricepsExtension,
    SeatedSingleArmOverheadDumbbellExtension,
    SingleArmDumbbellOverheadTricepsExtension,
    SingleDumbbellSeatedOverheadTricepsExtension,
    SingleLegBenchDipAndKick,
    SingleLegDip,
    StaticLyingTricepsExtension,
    SuspendedDip,
    SwissBallDumbbellLyingTricepsExtension,
    SwissBallEzBarLyingTricepsExtension,
    SwissBallEzBarOverheadTricepsExtension,
    TabletopDip,
    TricepsExtensionOnFloor,
    TricepsPressdown,
    WeightedBenchDip,
    WeightedDip,
    WeightedInclineDip,
    WeightedSingleLegBenchDipAndKick,
    WeightedSingleLegDip,
    WeightedSuspendedDip,
    WeightedTabletopDip,
    UnknownValue(u64),
}

impl From<FieldContent> for TricepsExtensionExerciseName {
    fn from(field: FieldContent) -> Self {
        if let FieldContent::UnsignedInt16(enum_value) = field {
            match enum_value {
                0 => TricepsExtensionExerciseName::BenchDip,
                1 => TricepsExtensionExerciseName::WeightedBenchDip,
                2 => TricepsExtensionExerciseName::BodyWeightDip,
                3 => TricepsExtensionExerciseName::CableKickback,
                4 => TricepsExtensionExerciseName::CableLyingTricepsExtension,
                5 => TricepsExtensionExerciseName::CableOverheadTricepsExtension,
                6 => TricepsExtensionExerciseName::DumbbellKickback,
                7 => TricepsExtensionExerciseName::DumbbellLyingTricepsExtension,
                8 => TricepsExtensionExerciseName::EzBarOverheadTricepsExtension,
                9 => TricepsExtensionExerciseName::InclineDip,
                10 => TricepsExtensionExerciseName::WeightedInclineDip,
                11 => TricepsExtensionExerciseName::InclineEzBarLyingTricepsExtension,
                12 => TricepsExtensionExerciseName::LyingDumbbellPulloverToExtension,
                13 => TricepsExtensionExerciseName::LyingEzBarTricepsExtension,
                14 => TricepsExtensionExerciseName::LyingTricepsExtensionToCloseGripBenchPress,
                15 => TricepsExtensionExerciseName::OverheadDumbbellTricepsExtension,
                16 => TricepsExtensionExerciseName::RecliningTricepsPress,
                17 => TricepsExtensionExerciseName::ReverseGripPressdown,
                18 => TricepsExtensionExerciseName::ReverseGripTricepsPressdown,
                19 => TricepsExtensionExerciseName::RopePressdown,
                20 => TricepsExtensionExerciseName::SeatedBarbellOverheadTricepsExtension,
                21 => TricepsExtensionExerciseName::SeatedDumbbellOverheadTricepsExtension,
                22 => TricepsExtensionExerciseName::SeatedEzBarOverheadTricepsExtension,
                23 => TricepsExtensionExerciseName::SeatedSingleArmOverheadDumbbellExtension,
                24 => TricepsExtensionExerciseName::SingleArmDumbbellOverheadTricepsExtension,
                25 => TricepsExtensionExerciseName::SingleDumbbellSeatedOverheadTricepsExtension,
                26 => TricepsExtensionExerciseName::SingleLegBenchDipAndKick,
                27 => TricepsExtensionExerciseName::WeightedSingleLegBenchDipAndKick,
                28 => TricepsExtensionExerciseName::SingleLegDip,
                29 => TricepsExtensionExerciseName::WeightedSingleLegDip,
                30 => TricepsExtensionExerciseName::StaticLyingTricepsExtension,
                31 => TricepsExtensionExerciseName::SuspendedDip,
                32 => TricepsExtensionExerciseName::WeightedSuspendedDip,
                33 => TricepsExtensionExerciseName::SwissBallDumbbellLyingTricepsExtension,
                34 => TricepsExtensionExerciseName::SwissBallEzBarLyingTricepsExtension,
                35 => TricepsExtensionExerciseName::SwissBallEzBarOverheadTricepsExtension,
                36 => TricepsExtensionExerciseName::TabletopDip,
                37 => TricepsExtensionExerciseName::WeightedTabletopDip,
                38 => TricepsExtensionExerciseName::TricepsExtensionOnFloor,
                39 => TricepsExtensionExerciseName::TricepsPressdown,
                40 => TricepsExtensionExerciseName::WeightedDip,
                n => TricepsExtensionExerciseName::UnknownValue(n as u64),
            }
        } else {
          panic!("can't convert TricepsExtensionExerciseName to {:?}", field);
        }
    }
}
