use crate::fields::FieldContent;
use serde::Serialize;

#[derive(Clone, Copy, Debug, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum WeatherSevereType {
    AirQuality,
    AirStagnation,
    ArcticOutflow,
    ArealFlood,
    Ashfall,
    Avalanche,
    Blizzard,
    BlowingDust,
    BlowingSnow,
    BriskWind,
    CoastalFlood,
    ColdWave,
    DebrisFlow,
    DenseFog,
    DenseSmoke,
    DustStorm,
    ExcessiveHeat,
    ExtremeCold,
    ExtremeWind,
    FireWeather,
    FlashFlood,
    FlashFreeze,
    Flood,
    Freeze,
    FreezingDrizzle,
    FreezingFog,
    FreezingRain,
    FreezingSpray,
    Frost,
    Gale,
    HardFreeze,
    HazardousSeas,
    Heat,
    HeavyFreezingSpray,
    HeavySnowAlert,
    HighHeatAndHumidity,
    HighSurf,
    HighWaterLevel,
    HighWind,
    Humidex,
    HumidexAndHealth,
    Hurricane,
    HurricaneForceWind,
    Hydrological,
    IceStorm,
    InlandHurricane,
    InlandTropicalStorm,
    LakeEffectBlowingSnow,
    LakeEffectSnow,
    LakeWind,
    LakeshoreFlood,
    LesSuetesWind,
    LowWater,
    MarineWeather,
    Rainfall,
    RipTide,
    SevereThunderstorm,
    Sleet,
    SmallCraft,
    SmallCraftHazardousSeas,
    SmallCraftRoughBar,
    SmallCraftWinds,
    Smog,
    SnowAlert,
    SnowAndBlowingSnow,
    SnowSquall,
    Snowfall,
    SpecialMarine,
    SpecialWeather,
    Squall,
    Storm,
    StormSurge,
    StrongWind,
    Tornado,
    TropicalStorm,
    Tsunami,
    Typhoon,
    Unspecified,
    Waterspout,
    Weather,
    Wind,
    WindChill,
    WinterStorm,
    WinterWeather,
    WreckhouseWinds,
    UnknownValue(u64),
}

impl From<FieldContent> for WeatherSevereType {
    fn from(field: FieldContent) -> Self {
        if let FieldContent::Enum(enum_value) = field {
            match enum_value {
                0 => WeatherSevereType::Unspecified,
                1 => WeatherSevereType::Tornado,
                2 => WeatherSevereType::Tsunami,
                3 => WeatherSevereType::Hurricane,
                4 => WeatherSevereType::ExtremeWind,
                5 => WeatherSevereType::Typhoon,
                6 => WeatherSevereType::InlandHurricane,
                7 => WeatherSevereType::HurricaneForceWind,
                8 => WeatherSevereType::Waterspout,
                9 => WeatherSevereType::SevereThunderstorm,
                10 => WeatherSevereType::WreckhouseWinds,
                11 => WeatherSevereType::LesSuetesWind,
                12 => WeatherSevereType::Avalanche,
                13 => WeatherSevereType::FlashFlood,
                14 => WeatherSevereType::TropicalStorm,
                15 => WeatherSevereType::InlandTropicalStorm,
                16 => WeatherSevereType::Blizzard,
                17 => WeatherSevereType::IceStorm,
                18 => WeatherSevereType::FreezingRain,
                19 => WeatherSevereType::DebrisFlow,
                20 => WeatherSevereType::FlashFreeze,
                21 => WeatherSevereType::DustStorm,
                22 => WeatherSevereType::HighWind,
                23 => WeatherSevereType::WinterStorm,
                24 => WeatherSevereType::HeavyFreezingSpray,
                25 => WeatherSevereType::ExtremeCold,
                26 => WeatherSevereType::WindChill,
                27 => WeatherSevereType::ColdWave,
                28 => WeatherSevereType::HeavySnowAlert,
                29 => WeatherSevereType::LakeEffectBlowingSnow,
                30 => WeatherSevereType::SnowSquall,
                31 => WeatherSevereType::LakeEffectSnow,
                32 => WeatherSevereType::WinterWeather,
                33 => WeatherSevereType::Sleet,
                34 => WeatherSevereType::Snowfall,
                35 => WeatherSevereType::SnowAndBlowingSnow,
                36 => WeatherSevereType::BlowingSnow,
                37 => WeatherSevereType::SnowAlert,
                38 => WeatherSevereType::ArcticOutflow,
                39 => WeatherSevereType::FreezingDrizzle,
                40 => WeatherSevereType::Storm,
                41 => WeatherSevereType::StormSurge,
                42 => WeatherSevereType::Rainfall,
                43 => WeatherSevereType::ArealFlood,
                44 => WeatherSevereType::CoastalFlood,
                45 => WeatherSevereType::LakeshoreFlood,
                46 => WeatherSevereType::ExcessiveHeat,
                47 => WeatherSevereType::Heat,
                48 => WeatherSevereType::Weather,
                49 => WeatherSevereType::HighHeatAndHumidity,
                50 => WeatherSevereType::HumidexAndHealth,
                51 => WeatherSevereType::Humidex,
                52 => WeatherSevereType::Gale,
                53 => WeatherSevereType::FreezingSpray,
                54 => WeatherSevereType::SpecialMarine,
                55 => WeatherSevereType::Squall,
                56 => WeatherSevereType::StrongWind,
                57 => WeatherSevereType::LakeWind,
                58 => WeatherSevereType::MarineWeather,
                59 => WeatherSevereType::Wind,
                60 => WeatherSevereType::SmallCraftHazardousSeas,
                61 => WeatherSevereType::HazardousSeas,
                62 => WeatherSevereType::SmallCraft,
                63 => WeatherSevereType::SmallCraftWinds,
                64 => WeatherSevereType::SmallCraftRoughBar,
                65 => WeatherSevereType::HighWaterLevel,
                66 => WeatherSevereType::Ashfall,
                67 => WeatherSevereType::FreezingFog,
                68 => WeatherSevereType::DenseFog,
                69 => WeatherSevereType::DenseSmoke,
                70 => WeatherSevereType::BlowingDust,
                71 => WeatherSevereType::HardFreeze,
                72 => WeatherSevereType::Freeze,
                73 => WeatherSevereType::Frost,
                74 => WeatherSevereType::FireWeather,
                75 => WeatherSevereType::Flood,
                76 => WeatherSevereType::RipTide,
                77 => WeatherSevereType::HighSurf,
                78 => WeatherSevereType::Smog,
                79 => WeatherSevereType::AirQuality,
                80 => WeatherSevereType::BriskWind,
                81 => WeatherSevereType::AirStagnation,
                82 => WeatherSevereType::LowWater,
                83 => WeatherSevereType::Hydrological,
                84 => WeatherSevereType::SpecialWeather,
                n => WeatherSevereType::UnknownValue(n as u64),
            }
        } else {
          panic!("can't convert WeatherSevereType to {:?}", field);
        }
    }
}
